kind: pipeline
name: default

platform:
  os: linux
  arch: arm64

steps:
- name: build
  image: plugins/docker:linux-arm64
  settings:
    repo: h3rj4n/imageproxy
    dockerfile: Dockerfile.arrm64v8
    tags:
      - latest
      - '0.7.0'
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
